blueprint:
  name: Light on/off
  description: Turn Light on/off based in time periods and state of the sun
  domain: automation
  input:
    switch_relay:
      name: Switch relay
      description: The relay the switch controls
      selector:
        entity:
          domain: switch
          device_class: outlet
    switch_light:
      name: Switch light
      description: The switch builtin green LED
      selector:
        entity:
          domain: light

trigger_variables:
  var_switch_relay: !input switch_relay
  
trigger:
  - platform: state
    entity_id: !input switch_relay
    id: switch_relay

action:
  - choose:
    - conditon: trigger
      id: switch_relay
    sequence:
      service: >
        {% if is_states('var_switch_relay', 'on') %}
          light.turn_on
        {% else %}
          light.turn_off
        {% endif %}
      target: !input switch_light
      message: Switch light
